= Columnar SDK Release Notes
:description: Release notes, brief installation instructions, and download archive for the Capella Columnar Node.js Client.
:navtitle: Release Notes
:page-toclevels: 2
:page-aliases: sdk-release-notes.adoc

// tag::all[]
[abstract]
{description}

Version {sdk_dot_minor} of the Node.js Columnar SDK implements the {sdk_api} xref:compatibility.adoc#api-version[SDK API].
See the xref:compatibility.html#couchbase-feature-availability-matrix[compatibility pages] for more information on feature compatibility with different versions of Capella columnar.


== Installation

See the xref:project-docs:sdk-full-installation.adoc[Full Installation] guide for details.

// tag::all[]


[#latest-release]
== Node.js Columnar SDK 1.0 Releases

We always recommend using the latest version of the SDK -- it contains all of the latest security patches and support for new and upcoming features.
All patch releases for each dot minor release should be API compatible, and safe to upgrade;
any changes to expected behavior are noted in the release notes that follow.


=== Version 1.0.1 (10 October 2025)

Version 1.0.1 is the next patch release of the first generation Couchbase Columnar Node.js SDK, bringing a number of improvements.

[source,bash]
----
$ npm install couchbase-columnar@1.0.1
----

*API Docs:* https://docs.couchbase.com/sdk-api/columnar-nodejs-client-1.0.1/

==== Enhancements

* https://jira.issues.couchbase.com/browse/JSCO-55[JSCO-55]:
Added support for Node.js 22.

* https://jira.issues.couchbase.com/browse/JSCO-56[JSCO-56]:
Added support for Node.js 24.

* https://jira.issues.couchbase.com/browse/JSCO-58[JSCO-58]:
Added support for building binary with sanitzers.

* https://jira.issues.couchbase.com/browse/JSCO-60[JSCO-60]:
Updated SDK to more recent {cpp} core.

==== Fixes

* https://jira.issues.couchbase.com/browse/JSCO-61[JSCO-61]:
The internal `OperationCanceledError` is no longer raised. Instead, `ColumnarError` is raised.

==== Known Issues

* https://jira.issues.couchbase.com/browse/JSCO-36[JSCO-36]: Logging hooks are not yet implemented.


=== Version 1.0.0 (11 October 2024)

This is the first General Availability (GA) release of the new Couchbase Columnar Node.js SDK.
It supports executing queries against Capella Columnar clusters, with additional features planned for future releases.

https://docs.couchbase.com/sdk-api/columnar-nodejs-client-1.0.0[API Reference^]

==== Known Issues

* https://jira.issues.couchbase.com/browse/JSCO-36[JSCO-36]: Logging hooks are not yet implemented.
// end::all[]
