= Compatibility
:description: Platform compatibility, and features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:page-toclevels: 3
:table-caption!:


[abstract]
{description}





== Platform Compatibility


=== Node.js Version Compatibility

The {sdk_dot_minor} Node.js SDK will run on recent LTS versions of Node.js: 20 and 22.
We recommend using the most recent long-term support (LTS) version of Node.js -- 
at the time of writing (October 2024) this is version 22.
 
TIP: Remember to keep your Node.js installation up to date, via `npm`.



=== OS Compatibility

include::{sdk_api}@columnar-sdk:shared:partial$compatibility.adoc[tag=os-compat]





=== Network Requirements

include::{sdk_api}@columnar-sdk:shared:partial$network-requirements.adoc[tag=lan-like]






== Capella Columnar Compatibility


Capella Columnar is a fully hosted service, continually updated, and offering the latest version --
with users having a few weeks to upgrade from the previous version.
As such, the latest Couchbase Columnar SDKs are tested against the latest versions.
Where older versions of the {name-sdk) pre-date significant new features in Columar, those differences will be noted in this section.


To make development easier, the SDK includes the Capella client certificate ready installed.






////
=== API Version

include::{sdk_api}@columnar-sdk:shared:partial$compatibility.adoc[tag=api-version]
////



== SDK API Stability


=== Interface Stability

include::{version-common}@columnar-sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]





////
=== Older SDK Versions

include::{version-common}@columnar-sdk:shared:partial$archive.adoc[tag=link]
////

////
Note the https://www.couchbase.com/support-policy[End of Life dates^] for {name-sdk} versions.
See the notes there for Support details.
////
