= Full Installation
:description: Installation instructions for the {name-sdk}.
:page-partial:


[abstract]
{description}





== Before You Start

The {sdk_dot_minor} Node.js SDK will run on recent LTS versions of Node.js: 20 and 22.
We recommend using the most recent long-term support (LTS) version of Node.js -- 
at the time of writing (October 2024) this is version 22.


== Getting the SDK


Eventually the SDK will be published to npm, but in the interim a select set of packages with prebuilt binaries are available on the https://github.com/couchbaselabs/columnar-nodejs-client/releases[GitHub Releases page].
If a packages is not available for your specific platform,
See the https://github.com/couchbaselabs/columnar-nodejs-client/blob/main/BUILDING.md[GitHub Building page] for details on how to build the SDK's binary.

To install the SDK from a package on the https://github.com/couchbaselabs/columnar-nodejs-client/releases[GitHub Releases page]:

. Download the appropriate package
. Unzip the downloaded file
. Install via npm: `npm install <path to unzipped wheel>`

If a compatible package is not available, the SDK's binary will need to be built from source:

* Follow the steps on the https://github.com/couchbaselabs/columnar-nodejs-client/blob/main/BUILDING.md[GitHub Building page].
* After the build succeeds, the SDK can be used by running Node scripts from within the cloned repository -- or the SDK can be installed via `npm`: `npm install <path to cloned repository>`.

