= Hello Columnar -- Node.js Columnar SDK

:lang: javascript
:example-source_commonjs: devguide:example$node/src/startusing_commonjs.js
:example-source-esmodules: devguide:example$node/src/startusing_esmodules.js
:example-source-lang: javascript

IMPORTANT: This page covers the pre-relase columnar SDK, for the internal preview, and remains applicable (internally) until the SDKs GA in October.
The other pages appearing in the left-hand nav are part of docs development towards GA, and may not be accurate until GA.

== Getting the SDK

Eventually the SDK will be published to npm, but in the interim a select set of packages with prebuilt binaries are available on the https://github.com/couchbaselabs/columnar-nodejs-client/releases[GitHub Releases page].
If a packages is not available for your specific platform,
See the https://github.com/couchbaselabs/columnar-nodejs-client/blob/main/BUILDING.md[GitHub Building page] for details on how to build the SDK's binary.

To install the SDK from a package on the https://github.com/couchbaselabs/columnar-nodejs-client/releases[GitHub Releases page]:

. Download the appropriate package
. Unzip the downloaded file
. Install via npm: `npm install <path to unzipped wheel>`

If a compatible package is not available, the SDK's binary will need to be built from source:

* Follow the steps on the https://github.com/couchbaselabs/columnar-nodejs-client/blob/main/BUILDING.md[GitHub Building page].
* After the build succeeds, the SDK can be used by running Node scripts from within the cloned repository -- or the SDK can be installed via `npm`: `npm install <path to cloned repository>`.


== Connecting and Executing a Query

=== CommonJS

[source,{example-source-lang}]
----
include::{example-source_commonjs}[indent=0,tag=commonjs]
----

=== ES Modules

[source,{example-source-lang}]
----
include::{example-source-esmodules}[indent=0,tag=esmodules]
----
